---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-dev-deploy
spec:
  selector:
    matchLabels:
      run: laravel-dev
  template:
    metadata:
      labels:
        run: laravel-dev
    spec:
      containers:
      - name: dev
        image: "235537379753.dkr.ecr.us-east-1.amazonaws.com/git-ops-dev:b76e90cadb6c36e2f53d59dc1ce23ab3ba1c23fd"
        ports:
        - containerPort: 80
        env:
        - name: APP_KEY
          value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
