---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-kubernetes-demo
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      run: laravel-kubernetes-demo
  template:
    metadata:
      labels:
        run: laravel-kubernetes-demo
    spec:
      containers:
      - name: demo
        image: "235537379753.dkr.ecr.us-east-1.amazonaws.com/git-ops-dev:1a23b2d05170eca7962422bc623cb4e7e2e1c1e7"
        ports:
        - containerPort: 80
        env:
        - name: APP_KEY
          value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
