---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-kubernetes-demo
spec:
  selector:
    matchLabels:
      run: laravel-kubernetes-demo
  template:
    metadata:
      labels:
        run: laravel-kubernetes-demo
    spec:
      containers:
      - name: demo
        image: "235537379753.dkr.ecr.us-east-1.amazonaws.com/git-ops-dev:ac76e268d48df1f287b221e605049c7fb592032b"
        ports:
        - containerPort: 80
        env:
        - name: APP_KEY
          value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
