---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-dev-deploy
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      run: laravel-dev
  template:
    metadata:
      labels:
        run: laravel-dev
    spec:
      containers:
      - name: dev
        image: "235537379753.dkr.ecr.us-east-1.amazonaws.com/git-ops-dev:c81279f9ddaf6e29ec7f2d0c95ceccaa06aebada"
        ports:
        - containerPort: 80
        env:
        - name: APP_KEY
          value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
