---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  selector:
    matchLabels:
      run: laravel
  template:
    metadata:
      labels:
        run: laravel
    spec:
      containers:
      - name: master
        image: "235537379753.dkr.ecr.us-east-1.amazonaws.com/git-ops-master:0d9fcf91bc11614343c2b47c5c8dcf84a0fc641a"
        ports:
        - containerPort: 80
        env:
        - name: APP_KEY
          value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
